version: '3.4'

services:
  postgres:
    image: postgres:11.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
  nats:
    image: nats:2.1.0
    expose:
      - 4222
      - 8222
      - 6222
  app:
    build: .
    depends_on:
      - postgres
      - nats
    environment:
      - NATS_HOSTNAME=nats
    volumes:
      - packages:/opt/mix
      - .:/app:delegated
      - archives:/app/.mix
    expose:
      - 4000

volumes:
  postgres:
  archives:
  packages:
